name: fluentui_icons
description: Microsoft Fluent UI Icons package for Flutter based on the official repo
version: 0.3.0
homepage: https://github.com/polilluminato/fluentui-icons
issue_tracker: https://github.com/polilluminato/fluentui-icons/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family:  FluentSystemIconsP1
      fonts:
        - asset: fonts/FluentSystemIconsP1.ttf
    - family:  FluentSystemIconsP2
      fonts:
        - asset: fonts/FluentSystemIconsP2.ttf
    - family:  FluentSystemIconsP3
      fonts:
        - asset: fonts/FluentSystemIconsP3.ttf
    - family:  FluentSystemIconsP4
      fonts:
        - asset: fonts/FluentSystemIconsP4.ttf
    - family:  FluentSystemIconsP5
      fonts:
        - asset: fonts/FluentSystemIconsP5.ttf
    - family:  FluentSystemIconsP6
      fonts:
        - asset: fonts/FluentSystemIconsP6.ttf
    - family:  FluentSystemIconsP7
      fonts:
        - asset: fonts/FluentSystemIconsP7.ttf
